# Generated by Django 6.0.3 on 2026-04-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_set1', '0007_quote_provider_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='provider',
            field=models.CharField(choices=[('qic', 'QIC Insurance UAE'), ('dic', 'DIC Insurance Broker UAE')], max_length=50),
        ),
    ]
